SET SERVEROUTPUT ON SIZE UNLIMITED
SET ECHO OFF
SET FEEDBACK ON

@01_CREATE_DATABASE.sql
@02_INDEXES.sql
@03_VIEWS_FUNCTIONS.sql
@04_PROCEDURES.sql
@05_TRIGGERS.sql
@06_BACKUP_STRATEGY.sql
@07_TEST_DATA.sql

-- Wyświetl podsumowanie obiektów
SELECT 'TABELE' AS OBIEKT, COUNT(*) AS LICZBA FROM user_tables
UNION ALL
SELECT 'SEKWENCJE', COUNT(*) FROM user_sequences
UNION ALL
SELECT 'WIDOKI', COUNT(*) FROM user_views
UNION ALL
SELECT 'FUNKCJE', COUNT(*) FROM user_procedures WHERE object_type = 'FUNCTION'
UNION ALL
SELECT 'PROCEDURY', COUNT(*) FROM user_procedures WHERE object_type = 'PROCEDURE'
UNION ALL
SELECT 'WYZWALACZE', COUNT(*) FROM user_triggers
UNION ALL
SELECT 'INDEKSY', COUNT(*) FROM user_indexes WHERE index_type = 'NORMAL';

